viewer = siteviewer(Buildings="map.osm",Basemap="topographic");

tx = txsite(Name="Small cell transmitter", ...
    Latitude=46.769840, ...
    Longitude=23.589682, ...
    AntennaHeight=10, ... % Increased height for better coverage
    TransmitterPower=10, ... % Higher power for extended range
    TransmitterFrequency=28e9); % 700 MHz for better propagation
show(tx)

rtpm = propagationModel("raytracing", ...
    Method="sbr", ...
    MaxNumReflections=0, ...
    BuildingsMaterial="perfect-reflector", ...
    TerrainMaterial="perfect-reflector");

coverage(tx,rtpm, ...
    SignalStrengths=-120:-5, ...
    MaxRange=250, ...
    Resolution=3, ...
    Transparency=0.6)



rx = rxsite(Name="Small cell receiver", ...
    Latitude=46.768527, ...
    Longitude=23.589499, ...
    AntennaHeight=1);

los(tx,rx)

rtpm.MaxNumReflections = 1;
clearMap(viewer)
raytrace(tx,rx,rtpm)

ss = sigstrength(rx,tx,rtpm);
disp("Received power using perfect reflection: " + ss + " dBm")